### ISSUE TITLE
Support multiple terraform source locations

### ISSUE THREAD

**Issue by dave-pollock** [gruntwork-io/terragrunt#113]
I am following the basic approach outlined in the Terragrunt docs under "Remote Terraform Configurations" and hitting a problem using modules. Let me know if I'm missing something.

An example of my project structure is:
* terraform
  * environments
    * stage
      * frontend-app
        └ .terragrunt   <-- uses "./../../../modules/frontend-app" as terraform source
        └ terraform.tfvars
      * backend-app
        └ .terragrunt
        └ terraform.tfvars
  * modules
    * reusable_module
      └ main.tf
    * frontend-app
        └ main.tf <-- contains a module using "${path.module}/../reusable_module" as source
    * backend-app
        └ main.tf

The issue is, Terragrunt will copy the files from modules/frontend-app to a temp directory and execute Terraform, but the reusable_module module source path is no longer valid. This means in order to use modules I need to either:
 - Use another source type such as GitHub, but I'd prefer to use the locally checked out copy during development.
 - Hard code the full path to the module (obviously bad).

I'm thinking simply adding the option to specify multiple source paths for terragrunt to copy into the temp directory would solve this. Something like:

```
terraform {
  source = [
    "./../../../modules/frontend-app",
    "./../../../modules/reusable_module"
  ]
}
```
Does this sound like a good solution or am I on the wrong track?

**Comment by brikis98** [comment]
Good point. This is definitely something we need to fix. We need a way for the `source` usage to take into account that your Terraform code may contain relative paths pointing to files outside of the module.

A list of `source` URLs is one option, but a little tedious. Another option is to specify a root `source` that Terragrunt downloads and a way to separately specify the working directory within that root. Something like:

```hcl
terraform {
  source {
    root = "../../../modules"
    working_dir = "frontend-app"
  }
}
```

Terragrunt would download `root` and `cd` into `${root}/${working_dir}`. I'll need to think on this one a bit more.

**Comment by brikis98** [comment]
Actually, thinking about it more, the syntax doesn't necessarily have to change. Terraform's `source` URLs, at least for Git URLs, already take this into account. Consider:

```hcl
terraform {
  source = "github.com/foo/bar.git//frontend-app"
}
```

The double-slash (`//`) separates the repo from the folder you want. Terragrunt could check out the entire repo and then `cd` into the folder you want. 

It's a little odd looking, but things seem to work just fine if you use a double-slash with local file paths too:

```hcl
terraform {
  source = "../../../modules//frontend-app"
}
```

This sort of path works just fine with `terraform init` (which is what we use to download or copy Terraform code), so I could update Terragrunt to look for a double-slash, download the entire contents of the part to the left of it, and then `cd` into the folder to the right of it. That should make most relative URLs work correctly...

**Comment by dave-pollock** [comment]
That sounds like a good solution to me brikis :)

**Comment by brikis98** [comment]
Should be fixed by #121 and available in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.9.9.

**Comment by dave-pollock** [comment]
Thanks @brikis98 !

**Comment by damon-atkins** [comment]
The resolution here still does not support grouping of modules.....
terragrunt.hcl -> calls module frontend-app which calls module elb, the solution above assumes elb is in the same repo

source = "github.com/foo/aws_service_abc.git//frontend-app" needs to use elb from ws_network.git
source = "github.com/foo/aws_network.git//elb"

It would be nice to have some low level modules which are within a repo or individual repo.    And have high level modules which call the low level modules stored in separate repos.
