### ISSUE TITLE
[MacOS] terragrunt console - Setctty set but Ctty not valid in child

### ISSUE THREAD

**Issue by niranjan94** [gruntwork-io/terragrunt#1329]
While trying to invoke the `terraform console` command via `terragrunt console`, 

I get the following error:

```
[terragrunt] 2020/09/07 14:30:52 Running command: terraform console
[terragrunt] 2020/09/07 14:30:52 Error closing pty: invalid argument
[terragrunt] 2020/09/07 14:30:52 Hit multiple errors:
fork/exec /usr/local/bin/terraform: Setctty set but Ctty not valid in child
[terragrunt] 2020/09/07 14:30:52 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

But this seems to work fine on Ubuntu.

---

**Versions:**

```
terragrunt version v0.23.40
Terraform v0.13.2
MacOS Catalina 10.15.6
```

**Comment by niranjan94** [comment]
On checking this further, this seems to be a regression. Terraform console works perfectly with terragrunt `v0.23.33`

**Comment by brikis98** [comment]
Thanks for reporting! If anyone has some time to [browse what changed between the two versions](https://github.com/gruntwork-io/terragrunt/compare/v0.23.33...v0.23.40) and help us spot the bug, that would be much appreciated!

**Comment by zdcthomas** [comment]
I've hit this same error recently on terragrunt `v0.24.1`. Is there something else I should be looking at here?

**Comment by niranjan94** [comment]
This issue got resolved in `v0.26.1` for me

**Comment by boonchu** [comment]
After upgrading to version 0.26.7, I still see the same issue.  

```
$ terragrunt --version
terragrunt version v0.26.7

... 

[terragrunt] 2020/12/01 15:57:08 Error closing pty: invalid argument
[terragrunt] 2020/12/01 15:57:08 Hit multiple errors:
fork/exec /usr/local/bin/terraform: Setctty set but Ctty not valid in child
```

**Comment by viljemskornik** [comment]
Upgrading to creack/pty to 1.1.10 should do the trick. Tested on my local build and it fixed the problem.

More at https://github.com/creack/pty/issues/96.

**Comment by moos3** [comment]
Any progress on getting this in to the next release?

**Comment by arash-bizcover** [comment]
also getting same error on v0.28.2 (on linux)

**Comment by abohne** [comment]
Still seeing this in terragrunt 0.28.8 on MacOS 10.15.7

**Comment by brikis98** [comment]
Please give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.13 a shot (binaries should show up shortly).

**Comment by IshwaryaMullaiSelvapandian** [comment]
Still seeing this error on terragrunt v0.29.2
