### ISSUE TITLE
aws-provider-patch data types

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/terragrunt#1709]
The `aws-provider-patch` command converts list inputs to a string, causing problems when the values are replaced.

E.g, `terragrunt aws-provider-patch --terragrunt-override-attr allowed_account_ids=["0000012345636"]` sets the `allowed_account_ids` to `"[0000012345636]"`.

**Comment by worldofgeese** [comment]
Thanks for filing this! Just to clarify it appears `aws-provider-patch` strips the inner string "0000012345636" in the conversion, causing `allowed_account_ids=["0000012345636"]` to format to `allowed_account_ids=[0000012345636]`

**Comment by yorinasub17** [comment]
Ah thanks for the clarification! Updated the OP description to include that.

**Comment by worldofgeese** [comment]
Using the latest service catalog `v0.41.3` I'm seeing a new resource, `logs-account-resources.tf` at the root of the cache directory for `account-baseline-root` which is not patched by the `aws-provider-patch` command:

**Comment by yorinasub17** [comment]
Just released a fix for the OP issue in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.30.0. Binaries will show up shortly.

**Comment by worldofgeese** [comment]
@yorinasub17 thanks for the new release! I can confirm it fixes the issue except in `logs-account-resources.tf` I documented in my earlier comment at https://github.com/gruntwork-io/terragrunt/issues/1709#issuecomment-859015761.

Below is the error log:
```
│ Error: Invalid provider configuration
│
│ on /home/taohansen/projects/famly-iac/try-famly_co/\_global/account_baseline/.terragrunt-cache/3sG4RTcgiUHDXHcFEn80XRjyrAQ/fCw8UgbtyEKZwmAHcT_oAWkqDzs/modules/landi
ngzone/account-baseline-root/logs-account-resources.tf line 131:
│ 131: provider "aws" {
│
│ The configuration for provider["registry.terraform.io/hashicorp/aws"].logs
│ depends on values that cannot be determined until apply.
╵

ERRO[0024] 1 error occurred: \* exit status 1
```

**Comment by yorinasub17** [comment]
This specific issue should be fixed. Don't remember why I reopened this ticket, but no further action is needed on the original ticket. The issue about the account-baseline module should be an issue in that repo.

**Comment by silvinobarreiros** [comment]
@yorinasub17 did you open another issue for the service catalog?

I'm also still seeing this:

```
│ Error: Invalid provider configuration
│
│ on /home/taohansen/projects/famly-iac/try-famly_co/\_global/account_baseline/.terragrunt-cache/3sG4RTcgiUHDXHcFEn80XRjyrAQ/fCw8UgbtyEKZwmAHcT_oAWkqDzs/modules/landi
ngzone/account-baseline-root/logs-account-resources.tf line 131:
│ 131: provider "aws" {
│
│ The configuration for provider["registry.terraform.io/hashicorp/aws"].logs
│ depends on values that cannot be determined until apply.
╵

ERRO[0024] 1 error occurred: \* exit status 1
```

**Comment by yorinasub17** [comment]
Hi, please open a new ticket in `terraform-aws-service-catalog`, with details on what steps you took to end up with that error and we can take a look. Thanks!
