### ISSUE TITLE
 Could not find .tflint.hcl config file in the parent folders when using TERRAGRUNT_DOWNLOAD env

### ISSUE THREAD

**Issue by lukasmrtvy** [gruntwork-io/terragrunt#2471]
Reproducer:
```
mkdir demo
mkdir -p modules/foo
touch modules/foo/main.tf
cat > demo/.tflint.hcl <<-END
  config { format = "compact" }
END
cat > demo/terragrunt.hcl <<-END
  terraform {
    source = "../modules//foo"
    before_hook "lint" {
      commands = ["validate"]
      execute  = ["tflint"]
    }
  }
END
TERRAGRUNT_DOWNLOAD=/tmp/.terragrunt-cache terragrunt validate --terragrunt-working-dir demo
```

**Comment by denis256** [comment]
Fix released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.44.5

**Comment by joaocc** [comment]
v0.49.1, this still happens even if TERRAGRUNT_DOWNLOAD is used.
