### ISSUE TITLE
Using provider caching with existing `.terraformrc` having `provider_installation` block defined.

### ISSUE THREAD

**Issue by nuryupin-kr** [gruntwork-io/terragrunt#3278]
## Describe the bug

I am trying to configure provider caching for `run-all` commands. I'm appending `--terragrunt-provider-cache` flag as shown in the [provider caching article](https://terragrunt.gruntwork.io/docs/features/provider-cache/). However, I can't get it to work, due to us having an existing `.terraformrc` file with the following configuration:
```hcl
provider_installation {
    direct {
        exclude = ["registry.terraform.io/*/*"]
    }
    filesystem_mirror {
        path = "hcl-file-working-directory-on-the-ci-cd-runner/terraform.d/plugins/"
        include = ["registry.terraform.io/manually-downloaded/provider"] 
    }
    network_mirror {
        url = "https://myorg.jfrog.io/artifactory/api/terraform/terraform-registry-prod/providers/"
        exclude = ["registry.terraform.io/manually-downloaded/provider"]
    }
}
```
We use `network_mirror` to download providers from our organizational artifactory registry, instead of using default terraform registry. Also, we have one provider that we download manually in our CI/CD workflow and then use `filesystem_mirror` to specify the directory we downloaded it to.

Also, since we are running our infrastructure in Github Actions we set `TF_CLI_CONFIG_FILE` env var to point to the path of our `.terraformrc`. Provider caching article [talks about Terragrunt setting that variable under the hood](https://terragrunt.gruntwork.io/docs/features/provider-cache/#how-terragrunt-provider-caching-works) to point to its own config file so I'm not sure if this could be my issue.

All of the providers are failing to download:
![image](https://github.com/user-attachments/assets/dc2d5337-4cd8-4e35-b2f0-14d2c32615d6)

Is it currently possible to make provider caching work with existing `provider_installation` block?
I couldn't find any documentation.

### When NOT using `provieder_installation` block:
When running configuration without `provider_installation` block, Terragrunt is able to find all the providers except for the one we pre-download into `hcl-file-working-directory-on-the-ci-cd-runner/terraform.d/plugins/registry.terraform.io/manually-downloaded/provider` before calling Terragrunt. Because it is placed under `terraform.d/plugins/` within the working directory, Terraform knows how to find it by default. However, when using `--terragrunt-provider-cache` flag, Terragrunt is unable to find and install that provider.

I think this issue might be related https://github.com/gruntwork-io/terragrunt/issues/3244

## Steps To Reproduce

Run `terragrunt run-all plan --terragrunt-provider-cache`

## Expected behavior

Providers successfully installed.

## Nice to haves
Documentation on how to use Terragrunt provider caching with pre-defined `provider_installation` config.

## Versions

- Terragrunt version: 0.63.0
- Terraform version: 1.5.7
- Environment details: alpine based docker image running in Github Actions workflow.

**Comment by levkohimins** [comment]
Resolved in [v0.63.3](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.63.3) release.

**Comment by nuryupin-kr** [comment]
Unfortunately, v0.63.3 didn't fix it. Still seems like `network_mirror` doesn't get respected. The error says that it's trying to call default terraform registry to install providers instead of pulling it from jFrog as configured in our `.terraform.rc` file.

![image](https://github.com/user-attachments/assets/822c69fb-e3e3-4509-b185-3b5a11a83b13)
