### ISSUE TITLE
Add a way to supply credentials for a third-party registry when using Terragrunt Provider Cache

### ISSUE THREAD

**Issue by nuryupin-kr** [gruntwork-io/terragrunt#3298]
## Describe the bug
Would like to use Terragrunt provider cache feature with `run-all`. We execute Terragrunt workloads exclusively in Github Actions CI/CD pipelines. Since it is non-interactive we cannot use commands like `terraform login` to auth with third-party provider registries.

We have the following `.terraformrc` configuration file:
```hcl
provider_installation {
    direct {
        exclude = ["registry.terraform.io/*/*"]
    }
    filesystem_mirror {
        path = "hcl-file-working-directory-on-the-ci-cd-runner/terraform.d/plugins/"
        include = ["registry.terraform.io/manually-downloaded/provider"] 
    }
    network_mirror {
        url = "https://myorg.jfrog.io/artifactory/api/terraform/terraform-registry-prod/providers/" #<-- REQUIRES CREDENTIALS
        exclude = ["registry.terraform.io/manually-downloaded/provider"]
    }
}
```
The way we supply credential for `myorg.jfrog.io` is by setting env var: `TF_TOKEN_myorg_jfrog_io: ${{secrets.JFROG_API_KEY}}` which is automatically recognized by Terraform. However, the problem arises when attempting to enable Terragrunt Provider Cache, by setting following vars:
`TERRAGRUNT_PROVIDER_CACHE=1`
`TERRAGRUNT_PROVIDER_CACHE_REGISTRY_NAMES=myorg.jfrog.io`
We get the following error:
![image](https://github.com/user-attachments/assets/8b988d59-998f-460d-a9f9-8b39e1c5d6c9)

Terragrunt is unable to pass through credentials specified in `TF_TOKEN_myorg_jfrog_io`

## Expected behavior
Terragrunt is able to read credentials from `TF_TOKEN_` variables.
OR
Introduce new env var and cli flag to supply credentials when using Terragrunt Provider Cache

## Additional Context
We run around 15 Terragrunt workloads in the pipeline at the same time. Each of those calls around 20 different terraform modules using `run-all` feature of Terragrunt. This results in having to download mostly same providers 300 times which is extremely inefficient as well as overwhelming for provider registry server resulting in provider querying errors. It would be absolutely amazing to have Terragrunt Provider Cache working 😊
## Versions
- Terragrunt version: 0.63.6
- Terraform version: 1.5.7
- Environment details: alpine linux container in Github Actions runner.

## Related Issues
https://github.com/gruntwork-io/terragrunt/issues/3287
https://github.com/gruntwork-io/terragrunt/issues/3278

**Comment by lorengordon** [comment]
TIL about the `TF_TOKEN_...` env... It's not mentioned on the terraform environment variables page, https://developer.hashicorp.com/terraform/cli/config/environment-variables. I kept looking and eventually found the doc over here on the cli configuration page, https://developer.hashicorp.com/terraform/cli/config/config-file#environment-variable-credentials

**Comment by nuryupin-kr** [comment]
UPDATE:
I've also tried to use `credentials` block in the `.terraformrc` file instead of setting `TF_TOKEN...` env var but ended up with an exact same result.

**Comment by levkohimins** [comment]
> UPDATE: I've also tried to use `credentials` block in the `.terraformrc` file instead of setting `TF_TOKEN...` env var but ended up with an exact same result.

Yes, this will not work because Terragrunt Provider Cache is responsible for downloading assets and does not accept any credentials when making requests. I have already started working on this, the results will appear soon.

**Comment by levkohimins** [comment]
Resolved in [v0.64.2](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.64.2) release.

**Comment by nuryupin-kr** [comment]
@levkohimins just tried v0.64.2 and seeing the exactly identical error. Tried both specifying credentials block and using an env var. Even tried to have them both and it still doesn't work. Had 'trace' level enabled for logs, but not seeing any useful info about why it may no worked 😞

**Comment by levkohimins** [comment]
Hey @nuryupin-kr,
I can't help you until you provide me with the actual configs, `.terraformrc`, and `terraform { required_providers { ...` from `*.tf`. Perhaps you could upload them to a private repository and give me access.

> UPDATE:
> It seems to be discovering the registry though:
> ![image](https://private-user-images.githubusercontent.com/94398695/353588146-efa3fc81-c475-4b26-bd55-4fcff5651281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTAwMDMsIm5iZiI6MTcyMjUwOTcwMywicGF0aCI6Ii85NDM5ODY5NS8zNTM1ODgxNDYtZWZhM2ZjODEtYzQ3NS00YjI2LWJkNTUtNGZjZmY1NjUxMjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEwNTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlODRiMzljZjVkNDQ4MDY2YTRlY2NmNzU5MDFkYTFmMGE3ZTBkNDkwMDIxZjdkMmIzOGZjNWE5MmExOWRmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kZq3E8-14VeNDGrZ8Y-Dg_bRbsbEo__-7_fbiugTzbw)

It is suspicious that the prefix "providers.v1" is empty.

**Comment by nuryupin-kr** [comment]
@levkohimins I spoke to my higher ups and unfortunately, I'm not allowed to share logs :( However, regarding `.terraformrc` - it's exactly as I showed in the original post, there is no other configuration, just the `provider_installation` block (except that I substituted real domain of course).

Here is required providers:
![image](https://github.com/user-attachments/assets/57a6b56f-53fd-441b-83c8-7d28fc0ae6ec)

**Comment by nuryupin-kr** [comment]
@levkohimins Should I create a new issue?

**Comment by levkohimins** [comment]
Hi @nuryupin-kr, sorry for taking so long to reply, I'm busy with another critical task right now. No, you don't need to create a new task, I am reopening this one.

**Comment by nuryupin-kr** [comment]
Hi @levkohimins. Is there any updates on this issue? Would love to hear back.

**Comment by yhakbar** [comment]
Hey folks, we can't prioritize this work, as (as far as I know) a pretty small minority of users experience this issue.

If a member of the community wants to take up the mantle of addressing the request, we are more than happy to support you develop a solution.

We have documentation on [contributing to Terragrunt](https://terragrunt.gruntwork.io/docs/community/contributing/#developing-terragrunt), and encourage you to join [our Discord](https://discord.gg/SPu4Degs5f) to chat with us directly if you need quick guidance on best practices.
